spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample_mysql?characterEncoding=UTF-8
    username: sample_user
    password: sample_userpw