spring:
  profiles: # profiles 설정
    active: dev # 다른 설정이 없을 때 default 환경 값
  devtools:
    livereload:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    format_sql: true